server:
  port: 8100
  servlet:
    context-path: "/me-leva-ai"
security:
      jwt:
        secret: "crescer-2018-2-java-jwt"
        expiration: 86400000 # 1 dia em milisegundos
      public:
        path: "/public/**"
spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: JAVA18
    password: JAVA18
    driver-class-name: oracle.jdbc.OracleDriver


