server:
    port: 8090
    servlet:
      context-path: "/tcc-java"
security:
      jwt:
        secret: "crescer-2018-2-java-jwt"
        expiration: 86400000 # 1 dia em milisegundos
      public:
        path: "/public/**"
spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: tcc18
    password: tcc18
    driver-class-name: oracle.jdbc.OracleDriver